### ISSUE TITLE
Release 0.0.11 has unsupported codec type :none (out_kafka_buffered.rb)

### ISSUE THREAD

**Issue by slydon-apixio** [htgc/fluent-plugin-kafka#14]
It looks like it is according to the spec for Poseidon online, but like :async it isn't actually a supported type.  I hard coded 'none' to 'nil' on line 24 to get this working in my environments.

**Comment by htgc** [comment]
Let me confirm.
I guess you're talking about :type of poseidon (https://github.com/bpot/poseidon/blob/master/lib/poseidon/producer.rb#L100, and it does not implemented yet.
However, I added support of :compression_codec (https://github.com/bpot/poseidon/blob/master/lib/poseidon/producer.rb#L104) at release 0.0.11, and it (:none also) has already support.

Please let me know if you have any concern or I made misunderstanding about this.

**Comment by slydon-apixio** [comment]
Sorry, I was still using poseidon 0.0.5.pre1 which didn't have :none.  poseidon 0.0.5 does correctly have it.
