### ISSUE TITLE
Support for partitioning

### ISSUE THREAD

**Issue by comtef** [htgc/fluent-plugin-kafka#17]
Hi,

I would like to know if partitioning is supported by the plugin.
Poseidon round robin messages by default but if a key is specified, it will use it to send the message to the related partition.

If it is supported, could you give an example of the fluentd configuration?
If not, do you have any plan to implement it?

Thanks,

Fabien

**Comment by htgc** [comment]
Hi @comtef,

I added to support partitioning.
you can set default_partition_key in config file, and also include 'partition_key' record in each message.

I also write description in README, please check it and let me know if you have any question.
Thanks,
