### ISSUE TITLE
max_bytes is not supported

### ISSUE THREAD

**Issue by hw6** [htgc/fluent-plugin-kafka#20]
Hi,

We have a Kafka topic where the  message.max.bytes at Kafka broker config is set to 3MB (default is 1MB). https://kafka.apache.org/08/configuration.html

Our Kafka consumer has to supply max_bytes to broker otherwise the connection will not allow us to pull data.

poseidon 's PartitionConsumer does support   max_bytes .   https://github.com/bpot/poseidon/blob/master/lib/poseidon/partition_consumer.rb#L53

Can you add the support for max_bytes option ?

Thanks.

Howard

**Comment by htgc** [comment]
Thank you for contribution, Howard!
I'll try to add this option in next release.

Thanks,
