### ISSUE TITLE
2015-08-14 13:20:09 +0800 [warn]: fluent/engine.rb:330:emit: no patterns matched tag="topic1"

### ISSUE THREAD

**Issue by w7374520** [htgc/fluent-plugin-kafka#22]
1.fluentd configure
[root@localhost fluent-plugin-kafka_0.15]# cat /etc/td-agent/td-agent.conf
<source>
  type   kafka
  topics topic1
  host   192.168.9.6
  port   9092
  format json
  #client_id TTTTTTTTTTTTTTTTTTTTTT
  max_bytes            1048576
  max_wait_ms        5000
  min_bytes             1
  socket_timeout_ms   50000
</source>

2.kafka describe topics
[root@localhost td-agent]# /usr/local/kafka/bin/kafka-topics.sh --describe --zookeeper 192.168.9.6:2181,192.168.9.7:2181,192.168.9.8:2181
[2015-08-14 13:47:54,456] WARN Connected to an old server; r-o mode will be unavailable (org.apache.zookeeper.ClientCnxnSocket)
Topic:topic1	PartitionCount:1	ReplicationFactor:3	Configs:
	Topic: topic1	Partition: 0	Leader: 1	Replicas: 1,2,0	Isr: 1,2,0

3.error log
2015-08-14 13:19:32 +0800 [warn]: fluent/engine.rb:330:emit: no patterns matched tag="topic1"
2015-08-14 13:19:32 +0800 [warn]: fluent/engine.rb:330:emit: no patterns matched tag="topic1"
2015-08-14 13:19:33 +0800 [warn]: fluent/engine.rb:330:emit: no patterns matched tag="topic1"
2015-08-14 13:20:09 +0800 [warn]: fluent/engine.rb:330:emit: no patterns matched tag="topic1"
2015-08-14 13:20:46 +0800 [warn]: fluent/engine.rb:330:emit: no patterns matched tag="topic1"

4.why ?
Why does it appear "patterns matched tag= no" "topic1" error log, what should I do? Look forward to your help... Thank you

**Comment by w7374520** [comment]
I need fluent from the above configuration Kafka consume

**Comment by htgc** [comment]
I am so sorry for my very late response.
The issue is `how to get data from kafka`, right?
Your configuration looks well if you're using `<source>` tag for that.
For example,
```
<source>
    type kafka
    topics topic1
    host 192.168.9.6
    port 9092
    format json
    #client_id TTTTTTTTTTTTTTTTTTTTTT
    max_bytes 1048576
    max_wait_ms 5000
    min_bytes 1
    socket_timeout_ms 50000
</source>
```
Could you check whether topic name `topic1` exists on your kafka environment again?
An error message appears if the topic you set doesn't exist when fluentd launched.

**Comment by w7374520** [comment]
Yes, my rsyslog.conf configured incorrectly. Thank you for your reply.
I have a suggestion, Input plugin can configure multiple host <broker host>, and record the offset, if a a broker fails, it can automatically connect the correct broker host, then you can do group_id between them。
Thank you for your reply, thank you

**Comment by htgc** [comment]
@w7374520 Thank you for your suggestion! Actually, @ymattw is contributing to use poseidon_cluster for clustering (https://github.com/htgc/fluent-plugin-kafka/issues/24) and @t-kitamura is contributing to store offset onto zookeeper (https://github.com/htgc/fluent-plugin-kafka/pull/27) as well :)
I would be happy if their contribution will satisfy your suggestion. Thank you,
