### ISSUE TITLE
the output Whether to support log_format, 

### ISSUE THREAD

**Issue by elain** [htgc/fluent-plugin-kafka#29]
Whether to support  logstash_format, 
such as https://github.com/uken/fluent-plugin-elasticsearch, 

logstash_format
logstash_format true # defaults to false
This is meant to make writing data into elasticsearch compatible to what logstash writes. By doing this, one could take advantade of kibana.

**Comment by htgc** [comment]
You mean you'd like to write data into elasticsearch via Kafka?
I think it's better to use [fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch) to store into elasticsearch. I don't think it's better solution to add dependency of another system into one plugin.

Anyway, you can configure as follows;
```
<match some.tag.**>
  type copy
  <store>
    type kafka
    : # Omit configuration about fluent-plugin-kafka
  </store>
  <store>
    type elasticsearch
    logstash_format true
    # Omit other configuration
  </store>
</match>
```

Please let me know your opinion. Thanks,

**Comment by elain** [comment]
Now I use fluentd to write directly to fluentd-plugin-elasticsearch through elasticsearch,
But I now want to use fluentd by fluentd-plugin-kafka written to Kafka, and then use the elasticsearch-river-kafka to read Kafka, written to the elasticsearch, consider that can rise to the effect of a disaster recovery, if es cluster down, log data can be temporarily stored in Kafka, ES cluster after recovery, and then from Kafka read write to es cluster, thus ensuring that log data in ES cluster。

I do not know this feasible? Or if there is a better way to make sure that the cluster ES does not throw the log data

**Comment by elain** [comment]
I solved this problem by modifying the output.rb, adding the logstash_time_format function, and later the code submitted to the

**Comment by elain** [comment]
http://www.elain.org/?p=990#more-990

**Comment by htgc** [comment]
Thank you for your code.
Basically, Fluentd has own buffering feature, so if you consider in case es is down, then Fluentd will store the data into buffer, and it will resend the data after es cluster recovered.
I think you don't need to use Kafka if you want to use Kafka only for buffering.

**Comment by elain** [comment]
I tested the buffer fluentd function, and found a long time will appear td-agent do not work, right, and I have a large amount of data, log or by the hour cutting, may be related to these two factors.

**Comment by htgc** [comment]
You should this issue on Fluentd mailing list. However, you can use Kafka for buffering but you can write by this output plugin, and pull them by input plugin or [kafka-fluent-consumer](https://github.com/treasure-data/kafka-fluentd-consumer), then write to elasticsearch by fluentd-plugin-elasticsearch. What do you think?
