### ISSUE TITLE
About partition, how can this configuration?

### ISSUE THREAD

**Issue by elain** [htgc/fluent-plugin-kafka#31]
My Kafka is one topic of 8 partitions,and I use input plugin, how to configure the parttion, then I read the all data?
I am currently configured as follows:
####################
<source>
  type   kafka
  #host   c3-b2c-b2cop-log-kafka01.bj,c3-b2c-b2cop-log-kafka02.bj,c3-b2c-b2cop-log-kafka03.bj
  host   c3-b2c-b2cop-log-kafka01.bj
  port   9092
  <topic>
    topic ngx_order_log
    partition   0
    offset      -1
  </topic>
  format json
  add_prefix new
</source>

<match *.**>
  type elasticsearch
  host 10.108.173.29
  port 9200
  path /
  logstash_format true
  utc_index false
  flush_interval 3s
  include_tag_key true
  tag_key tag
  num_threads 5
  logstash_prefix new_ngx_order_log
</match>
#################

However, so that I can only read one of the 8 points of the data, and can not read all。
If I configure the partition parameter to be 8, I just tip the error:

2015-10-22 11:00:30 +0800 [error]: Poseidon::Errors::UnknownTopicOrPartition
  2015-10-22 11:00:30 +0800 [error]: suppressed same stacktrace
2015-10-22 11:00:31 +0800 [error]: Poseidon::Errors::UnknownTopicOrPartition
  2015-10-22 11:00:31 +0800 [error]: suppressed same stacktrace

1、How I can read complete How to configure,？
2、If I use fluent-plugin-kafka to read data on multiple machines, how to configure?

**Comment by repeatedly** [comment]
> If I configure the partition parameter to be 8, I just tip the error:

Do you mean you can write following configuration?

```aconf
  <topic>
    topic ngx_order_log
    partition 0
    offset -1
  </topic>
  <topic>
    topic ngx_order_log
    partition 1
    offset -1
  </topic>
  ...
  <topic>
    topic ngx_order_log
    partition 7
    offset -1
  </topic>
```

**Comment by elain** [comment]
Thank you very much. I have tried this way, it seems that I don't support it.
But I use logstash to do this.

**Comment by repeatedly** [comment]
I see.
Lastet this plugin supports `kafka_gourp` and Treasure Data released kafka consumer for fluentd.

https://github.com/treasure-data/kafka-fluentd-consumer

If you have a change in the future, please try it.
