### ISSUE TITLE
can not use "${tag}" to config default_topic

### ISSUE THREAD

**Issue by DDAAREN** [htgc/fluent-plugin-kafka#42]
When i was trying to config like:

>  default_topic  prefix_${tag_parts[2]}

I got such message:

> Poseidon::Errors::UnableToFetchMetadata

**Comment by repeatedly** [comment]
This plugin doesn't support `${}` placeholder.
Please use forest plugin.

**Comment by foxracle** [comment]
> This plugin doesn't support `${}` placeholder.
> Please use forest plugin.

Does it support placeholder now?
how to support dynamic topic according to the tag, I mean each topic for each tag
