### ISSUE TITLE
install fluent-plugin-kafka proble

### ISSUE THREAD

**Issue by 467754239** [htgc/fluent-plugin-kafka#48]
$ sudo gem install fluent-plugin-kafka
Fetching: msgpack-0.5.12.gem (100%)
Building native extensions.  This could take a while...
Successfully installed msgpack-0.5.12
Fetching: yajl-ruby-1.2.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed yajl-ruby-1.2.1
Fetching: cool.io-1.4.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed cool.io-1.4.3
Fetching: http_parser.rb-0.6.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed http_parser.rb-0.6.0
Fetching: sigdump-0.2.4.gem (100%)
Successfully installed sigdump-0.2.4
Fetching: tzinfo-data-1.2016.1.gem (100%)
Successfully installed tzinfo-data-1.2016.1
Fetching: string-scrub-0.0.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed string-scrub-0.0.5
Fetching: fluentd-0.12.20.gem (100%)
Successfully installed fluentd-0.12.20
Fetching: poseidon-0.0.5.gem (100%)
Successfully installed poseidon-0.0.5
Fetching: zookeeper-1.4.11.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-kafka:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.0 extconf.rb
Building zkc.
tar xzf zkc-3.4.5.tar.gz 2>&1
patch -p0 < patches/zkc-3.4.5-yosemite-htonl-fix.patch 2>&1
sh: patch: command not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.0
extconf.rb:51:in `safe_sh': command failed! patch -p0 < patches/zkc-3.4.5-yosemite-htonl-fix.patch 2>&1 (RuntimeError)
	from extconf.rb:64:in `block (2 levels) in <main>'
	from extconf.rb:63:in `each'
	from extconf.rb:63:in `block in <main>'
	from extconf.rb:55:in `chdir'
	from extconf.rb:55:in `<main>'

Gem files will remain installed in /usr/local/share/ruby/gems/2.0/gems/zookeeper-1.4.11 for inspection.
Results logged to /usr/local/share/ruby/gems/2.0/gems/zookeeper-1.4.11/ext/gem_make.out

**Comment by 467754239** [comment]
^[[A[ec2-user@ip-172-31-49-174 ~]$ sudo /etc/init.d/td-agent start
Starting td-agent: 2016-03-28 07:50:14 +0000 [error]: fluent/supervisor.rb:359:rescue in main_process: config error file="/etc/td-agent/td-agent.conf" error="Unknown output plugin 'kafka'. Run 'gem search -rd fluent-plugin' to find plugins"
                                                           [FAILED]

**Comment by 467754239** [comment]
$ pwd
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems
[ec2-user@ip-172-31-49-174 gems]$ ls
actionmailer-4.2.1         draper-1.4.0                            http_parser.rb-0.6.0   nokogiri-1.6.7.2                  sprockets-rails-2.2.4
actionpack-4.2.1           erubis-2.7.0                            i18n-0.7.0             ohai-6.20.0                       string-scrub-0.0.5
actionview-4.2.1           fluentd-0.12.20                         ipaddress-0.8.2        oj-2.14.4                         sucker_punch-1.0.5
activejob-4.2.1            fluentd-ui-0.4.2                        jbuilder-2.2.6         parallel-0.6.5                    systemu-2.5.2
activemodel-4.2.1          fluent-logger-0.5.1                     jmespath-1.1.3         puma-2.11.1                       td-0.13.2
activerecord-4.2.1         fluent-mixin-config-placeholders-0.3.1  jquery-rails-3.1.2     rack-1.6.0                        td-client-0.8.78
activesupport-4.2.1        fluent-mixin-plaintextformatter-0.2.6   json-1.8.1             rack-test-0.6.3                   td-logger-0.3.25
addressable-2.3.8          fluent-plugin-kafka-0.1.3               kramdown-1.6.0         rails-4.2.1                       test-unit-2.1.8.0
addressable-2.4.0          fluent-plugin-mongo-0.7.12              kramdown-haml-0.0.3    rails-deprecated_sanitizer-1.0.3  thor-0.19.1
arel-5.0.1.20140414130214  fluent-plugin-rewrite-tag-filter-1.5.4  loofah-2.0.3           rails-dom-testing-1.0.7           thread_safe-0.3.5
arel-6.0.3                 fluent-plugin-s3-0.6.5                  ltsv-0.1.0             rails-html-sanitizer-1.0.3        thrift-0.8.0
aws-sdk-2.2.14             fluent-plugin-scribe-0.10.14            mail-2.6.3             railties-4.2.1                    tilt-1.4.1
aws-sdk-core-2.2.14        fluent-plugin-td-0.10.28                mime-types-2.4.3       rake-10.1.0                       timers-1.1.0
aws-sdk-resources-2.2.14   fluent-plugin-td-monitoring-0.2.2       mini_portile2-2.0.0    rdoc-4.1.0                        tzinfo-1.2.2
aws-sdk-v1-1.66.0          fluent-plugin-webhdfs-0.4.1             minitest-5.4.2         request_store-1.1.0               tzinfo-data-1.2016.1
bson-1.12.5                font-awesome-rails-4.3.0.0              mixlib-cli-1.5.0       ruby-progressbar-1.7.5            uuidtools-2.1.5
bson_ext-1.12.5            globalid-0.3.6                          mixlib-config-2.2.1    rubyzip-1.1.7                     webhdfs-0.7.4
builder-3.2.2              haml-4.0.6                              mixlib-log-1.6.0       sass-3.2.19                       yajl-ruby-1.2.1
bundler-1.10.6             haml-rails-0.5.3                        mixlib-shellout-2.2.6  sass-rails-4.0.5                  zip-zip-0.3
celluloid-0.15.2           hike-1.2.3                              mongo-1.12.5           settingslogic-2.0.9
cool.io-1.4.2              hirb-0.7.3                              msgpack-0.5.11         sigdump-0.2.3
diff-lcs-1.2.5             httpclient-2.7.1                        multi_json-1.11.0      sprockets-2.12.3

**Comment by 467754239** [comment]
drwxrwxr-x  4 root root 4096 Mar 28 07:49 fluent-plugin-kafka-0.1.3

**Comment by ymattw** [comment]
Dude, there was an error message clearly says what happened `sh: patch: command not found`.

**Comment by repeatedly** [comment]
Closed. If you still have a problem after installed development pacakges, please re-open this issue.
