### ISSUE TITLE
output can be define brokes by zookeeper

### ISSUE THREAD

**Issue by anfengdaydayup** [htgc/fluent-plugin-kafka#5]
if  output can be define brokes by zookeeper, became kafka brokes could Changed and some broke could be down。

eg.
<match *.**>
  type                kafka
  zookeepers    localhost:2181
  default_topic    <output topic>
</match>

**Comment by htgc** [comment]
Sorry for being super late...
I fixes this issue, and I'll upload to RubyGems as v0.0.9 soon.
Please try this version and let me know if you have still trouble.
Thank you for contributing!
